language: node_js

node_js:
  - "node"
  - "6"
  - "5"
  - "4"
sudo: false

install:
  - travis_retry npm install

after_success:
  - cat ./test/results/lcov.info | ./node_modules/coveralls/bin/coveralls.js
