name: Release

on:
  push:
    branches:
      - 'master'

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: write
  issues: write

jobs:
  main:
    runs-on: ubuntu-latest
    environment: DeployEnv
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm i
      - run: npm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
